// utils/city-data.js - 中国省市区三级数据
// 覆盖全国31个省级行政区，地级市全覆盖，区县精简为主要城区
module.exports = [
  { name: '北京市', children: [ { name: '北京市', children: [ { name: '东城区' }, { name: '西城区' }, { name: '朝阳区' }, { name: '丰台区' }, { name: '石景山区' }, { name: '海淀区' }, { name: '顺义区' }, { name: '通州区' }, { name: '大兴区' }, { name: '房山区' }, { name: '昌平区' }, { name: '怀柔区' }, { name: '平谷区' }, { name: '密云区' }, { name: '延庆区' }, { name: '门头沟区' } ] } ] },
  { name: '天津市', children: [ { name: '天津市', children: [ { name: '和平区' }, { name: '河东区' }, { name: '河西区' }, { name: '南开区' }, { name: '河北区' }, { name: '红桥区' }, { name: '东丽区' }, { name: '西青区' }, { name: '津南区' }, { name: '北辰区' }, { name: '武清区' }, { name: '宝坻区' }, { name: '滨海新区' }, { name: '宁河区' }, { name: '静海区' }, { name: '蓟州区' } ] } ] },
  { name: '上海市', children: [ { name: '上海市', children: [ { name: '黄浦区' }, { name: '徐汇区' }, { name: '长宁区' }, { name: '静安区' }, { name: '普陀区' }, { name: '虹口区' }, { name: '杨浦区' }, { name: '闵行区' }, { name: '宝山区' }, { name: '嘉定区' }, { name: '浦东新区' }, { name: '金山区' }, { name: '松江区' }, { name: '青浦区' }, { name: '奉贤区' }, { name: '崇明区' } ] } ] },
  { name: '重庆市', children: [ { name: '重庆市', children: [ { name: '万州区' }, { name: '涪陵区' }, { name: '渝中区' }, { name: '大渡口区' }, { name: '江北区' }, { name: '沙坪坝区' }, { name: '九龙坡区' }, { name: '南岸区' }, { name: '北碚区' }, { name: '綦江区' }, { name: '大足区' }, { name: '渝北区' }, { name: '巴南区' }, { name: '黔江区' }, { name: '长寿区' }, { name: '江津区' }, { name: '合川区' }, { name: '永川区' }, { name: '南川区' }, { name: '璧山区' }, { name: '铜梁区' }, { name: '潼南区' }, { name: '荣昌区' }, { name: '开州区' }, { name: '梁平区' }, { name: '武隆区' } ] } ] },

  { name: '河北省', children: [
    { name: '石家庄市', children: [ { name: '长安区' }, { name: '桥西区' }, { name: '新华区' }, { name: '裕华区' }, { name: '藁城区' } ] },
    { name: '唐山市', children: [ { name: '路南区' }, { name: '路北区' }, { name: '开平区' } ] },
    { name: '秦皇岛市', children: [ { name: '海港区' }, { name: '北戴河区' } ] },
    { name: '邯郸市', children: [ { name: '邯山区' }, { name: '丛台区' }, { name: '复兴区' } ] },
    { name: '邢台市', children: [ { name: '襄都区' }, { name: '信都区' } ] },
    { name: '保定市', children: [ { name: '竞秀区' }, { name: '莲池区' } ] },
    { name: '张家口市', children: [ { name: '桥东区' }, { name: '桥西区' } ] },
    { name: '承德市', children: [ { name: '双桥区' }, { name: '双滦区' } ] },
    { name: '沧州市', children: [ { name: '新华区' }, { name: '运河区' } ] },
    { name: '廊坊市', children: [ { name: '安次区' }, { name: '广阳区' } ] },
    { name: '衡水市', children: [ { name: '桃城区' }, { name: '冀州区' } ] },
  ]},
  { name: '山西省', children: [
    { name: '太原市', children: [ { name: '小店区' }, { name: '迎泽区' }, { name: '杏花岭区' } ] },
    { name: '大同市', children: [ { name: '平城区' }, { name: '云冈区' } ] },
    { name: '阳泉市', children: [ { name: '城区' }, { name: '矿区' } ] },
    { name: '长治市', children: [ { name: '潞州区' } ] },
    { name: '晋城市', children: [ { name: '城区' } ] },
    { name: '朔州市', children: [ { name: '朔城区' } ] },
    { name: '晋中市', children: [ { name: '榆次区' } ] },
    { name: '运城市', children: [ { name: '盐湖区' } ] },
    { name: '忻州市', children: [ { name: '忻府区' } ] },
    { name: '临汾市', children: [ { name: '尧都区' } ] },
    { name: '吕梁市', children: [ { name: '离石区' } ] },
  ]},
  { name: '内蒙古', children: [
    { name: '呼和浩特市', children: [ { name: '新城区' }, { name: '回民区' }, { name: '赛罕区' } ] },
    { name: '包头市', children: [ { name: '昆都仑区' }, { name: '青山区' } ] },
    { name: '乌海市', children: [ { name: '海勃湾区' } ] },
    { name: '赤峰市', children: [ { name: '红山区' }, { name: '松山区' } ] },
    { name: '通辽市', children: [ { name: '科尔沁区' } ] },
    { name: '鄂尔多斯市', children: [ { name: '东胜区' } ] },
    { name: '呼伦贝尔市', children: [ { name: '海拉尔区' } ] },
    { name: '巴彦淖尔市', children: [ { name: '临河区' } ] },
    { name: '乌兰察布市', children: [ { name: '集宁区' } ] },
    { name: '兴安盟', children: [ { name: '乌兰浩特市' } ] },
    { name: '锡林郭勒盟', children: [ { name: '锡林浩特市' } ] },
    { name: '阿拉善盟', children: [ { name: '阿拉善左旗' } ] },
  ]},
  { name: '辽宁省', children: [
    { name: '沈阳市', children: [ { name: '和平区' }, { name: '沈河区' }, { name: '皇姑区' }, { name: '铁西区' } ] },
    { name: '大连市', children: [ { name: '中山区' }, { name: '西岗区' }, { name: '沙河口区' }, { name: '甘井子区' } ] },
    { name: '鞍山市', children: [ { name: '铁东区' }, { name: '铁西区' } ] },
    { name: '抚顺市', children: [ { name: '新抚区' }, { name: '顺城区' } ] },
    { name: '本溪市', children: [ { name: '平山区' } ] },
    { name: '丹东市', children: [ { name: '振兴区' } ] },
    { name: '锦州市', children: [ { name: '太和区' } ] },
    { name: '营口市', children: [ { name: '站前区' } ] },
    { name: '阜新市', children: [ { name: '海州区' } ] },
    { name: '辽阳市', children: [ { name: '白塔区' } ] },
    { name: '盘锦市', children: [ { name: '兴隆台区' } ] },
    { name: '铁岭市', children: [ { name: '银州区' } ] },
    { name: '朝阳市', children: [ { name: '双塔区' } ] },
    { name: '葫芦岛市', children: [ { name: '连山区' } ] },
  ]},
  { name: '吉林省', children: [
    { name: '长春市', children: [ { name: '南关区' }, { name: '朝阳区' }, { name: '绿园区' } ] },
    { name: '吉林市', children: [ { name: '船营区' }, { name: '昌邑区' } ] },
    { name: '四平市', children: [ { name: '铁西区' } ] },
    { name: '辽源市', children: [ { name: '龙山区' } ] },
    { name: '通化市', children: [ { name: '东昌区' } ] },
    { name: '白山市', children: [ { name: '浑江区' } ] },
    { name: '松原市', children: [ { name: '宁江区' } ] },
    { name: '白城市', children: [ { name: '洮北区' } ] },
    { name: '延边州', children: [ { name: '延吉市' } ] },
  ]},
  { name: '黑龙江省', children: [
    { name: '哈尔滨市', children: [ { name: '道里区' }, { name: '南岗区' }, { name: '松北区' } ] },
    { name: '齐齐哈尔市', children: [ { name: '龙沙区' }, { name: '建华区' } ] },
    { name: '鸡西市', children: [ { name: '鸡冠区' } ] },
    { name: '鹤岗市', children: [ { name: '向阳区' } ] },
    { name: '双鸭山市', children: [ { name: '尖山区' } ] },
    { name: '大庆市', children: [ { name: '萨尔图区' } ] },
    { name: '伊春市', children: [ { name: '伊美区' } ] },
    { name: '佳木斯市', children: [ { name: '前进区' } ] },
    { name: '七台河市', children: [ { name: '桃山区' } ] },
    { name: '牡丹江市', children: [ { name: '东安区' } ] },
    { name: '黑河市', children: [ { name: '爱辉区' } ] },
    { name: '绥化市', children: [ { name: '北林区' } ] },
    { name: '大兴安岭', children: [ { name: '加格达奇区' } ] },
  ]},
  { name: '江苏省', children: [
    { name: '南京市', children: [ { name: '玄武区' }, { name: '秦淮区' }, { name: '鼓楼区' }, { name: '建邺区' }, { name: '江宁区' } ] },
    { name: '无锡市', children: [ { name: '梁溪区' }, { name: '滨湖区' } ] },
    { name: '徐州市', children: [ { name: '云龙区' }, { name: '泉山区' } ] },
    { name: '常州市', children: [ { name: '天宁区' }, { name: '新北区' } ] },
    { name: '苏州市', children: [ { name: '姑苏区' }, { name: '工业园区' } ] },
    { name: '南通市', children: [ { name: '崇川区' }, { name: '通州区' } ] },
    { name: '连云港市', children: [ { name: '海州区' } ] },
    { name: '淮安市', children: [ { name: '清江浦区' } ] },
    { name: '盐城市', children: [ { name: '亭湖区' } ] },
    { name: '扬州市', children: [ { name: '广陵区' }, { name: '邗江区' } ] },
    { name: '镇江市', children: [ { name: '京口区' }, { name: '润州区' } ] },
    { name: '泰州市', children: [ { name: '海陵区' } ] },
    { name: '宿迁市', children: [ { name: '宿城区' } ] },
  ]},
  { name: '浙江省', children: [
    { name: '杭州市', children: [ { name: '上城区' }, { name: '拱墅区' }, { name: '西湖区' }, { name: '滨江区' }, { name: '萧山区' } ] },
    { name: '宁波市', children: [ { name: '海曙区' }, { name: '鄞州区' }, { name: '江北区' } ] },
    { name: '温州市', children: [ { name: '鹿城区' }, { name: '龙湾区' } ] },
    { name: '嘉兴市', children: [ { name: '南湖区' } ] },
    { name: '湖州市', children: [ { name: '吴兴区' } ] },
    { name: '绍兴市', children: [ { name: '越城区' }, { name: '柯桥区' } ] },
    { name: '金华市', children: [ { name: '婺城区' }, { name: '金东区' } ] },
    { name: '衢州市', children: [ { name: '柯城区' } ] },
    { name: '舟山市', children: [ { name: '定海区' }, { name: '普陀区' } ] },
    { name: '台州市', children: [ { name: '椒江区' } ] },
    { name: '丽水市', children: [ { name: '莲都区' } ] },
  ]},
  { name: '安徽省', children: [
    { name: '合肥市', children: [ { name: '蜀山区' }, { name: '包河区' }, { name: '庐阳区' } ] },
    { name: '芜湖市', children: [ { name: '镜湖区' }, { name: '鸠江区' } ] },
    { name: '蚌埠市', children: [ { name: '蚌山区' } ] },
    { name: '淮南市', children: [ { name: '田家庵区' } ] },
    { name: '马鞍山市', children: [ { name: '花山区' } ] },
    { name: '淮北市', children: [ { name: '相山区' } ] },
    { name: '铜陵市', children: [ { name: '铜官区' } ] },
    { name: '安庆市', children: [ { name: '迎江区' } ] },
    { name: '黄山市', children: [ { name: '屯溪区' } ] },
    { name: '滁州市', children: [ { name: '琅琊区' } ] },
    { name: '阜阳市', children: [ { name: '颍州区' } ] },
    { name: '宿州市', children: [ { name: '埇桥区' } ] },
    { name: '六安市', children: [ { name: '金安区' } ] },
    { name: '亳州市', children: [ { name: '谯城区' } ] },
    { name: '池州市', children: [ { name: '贵池区' } ] },
    { name: '宣城市', children: [ { name: '宣州区' } ] },
  ]},
  { name: '福建省', children: [
    { name: '福州市', children: [ { name: '鼓楼区' }, { name: '台江区' }, { name: '仓山区' } ] },
    { name: '厦门市', children: [ { name: '思明区' }, { name: '湖里区' }, { name: '集美区' } ] },
    { name: '莆田市', children: [ { name: '城厢区' } ] },
    { name: '三明市', children: [ { name: '三元区' } ] },
    { name: '泉州市', children: [ { name: '丰泽区' }, { name: '鲤城区' } ] },
    { name: '漳州市', children: [ { name: '芗城区' } ] },
    { name: '南平市', children: [ { name: '建阳区' } ] },
    { name: '龙岩市', children: [ { name: '新罗区' } ] },
    { name: '宁德市', children: [ { name: '蕉城区' } ] },
  ]},
  { name: '江西省', children: [
    { name: '南昌市', children: [ { name: '东湖区' }, { name: '西湖区' }, { name: '青山湖区' } ] },
    { name: '景德镇市', children: [ { name: '珠山区' } ] },
    { name: '萍乡市', children: [ { name: '安源区' } ] },
    { name: '九江市', children: [ { name: '浔阳区' }, { name: '濂溪区' } ] },
    { name: '新余市', children: [ { name: '渝水区' } ] },
    { name: '鹰潭市', children: [ { name: '月湖区' } ] },
    { name: '赣州市', children: [ { name: '章贡区' } ] },
    { name: '吉安市', children: [ { name: '吉州区' } ] },
    { name: '宜春市', children: [ { name: '袁州区' } ] },
    { name: '抚州市', children: [ { name: '临川区' } ] },
    { name: '上饶市', children: [ { name: '信州区' } ] },
  ]},
  { name: '山东省', children: [
    { name: '济南市', children: [ { name: '历下区' }, { name: '市中区' }, { name: '槐荫区' } ] },
    { name: '青岛市', children: [ { name: '市南区' }, { name: '市北区' }, { name: '崂山区' } ] },
    { name: '淄博市', children: [ { name: '张店区' } ] },
    { name: '枣庄市', children: [ { name: '薛城区' } ] },
    { name: '东营市', children: [ { name: '东营区' } ] },
    { name: '烟台市', children: [ { name: '芝罘区' }, { name: '莱山区' } ] },
    { name: '潍坊市', children: [ { name: '奎文区' }, { name: '潍城区' } ] },
    { name: '济宁市', children: [ { name: '任城区' } ] },
    { name: '泰安市', children: [ { name: '泰山区' } ] },
    { name: '威海市', children: [ { name: '环翠区' } ] },
    { name: '日照市', children: [ { name: '东港区' } ] },
    { name: '临沂市', children: [ { name: '兰山区' } ] },
    { name: '德州市', children: [ { name: '德城区' } ] },
    { name: '聊城市', children: [ { name: '东昌府区' } ] },
    { name: '滨州市', children: [ { name: '滨城区' } ] },
    { name: '菏泽市', children: [ { name: '牡丹区' } ] },
  ]},
  { name: '河南省', children: [
    { name: '郑州市', children: [ { name: '中原区' }, { name: '金水区' }, { name: '二七区' } ] },
    { name: '开封市', children: [ { name: '龙亭区' }, { name: '鼓楼区' } ] },
    { name: '洛阳市', children: [ { name: '洛龙区' }, { name: '西工区' } ] },
    { name: '平顶山市', children: [ { name: '新华区' } ] },
    { name: '安阳市', children: [ { name: '文峰区' } ] },
    { name: '鹤壁市', children: [ { name: '淇滨区' } ] },
    { name: '新乡市', children: [ { name: '红旗区' } ] },
    { name: '焦作市', children: [ { name: '解放区' } ] },
    { name: '濮阳市', children: [ { name: '华龙区' } ] },
    { name: '许昌市', children: [ { name: '魏都区' } ] },
    { name: '漯河市', children: [ { name: '源汇区' } ] },
    { name: '三门峡市', children: [ { name: '湖滨区' } ] },
    { name: '南阳市', children: [ { name: '卧龙区' } ] },
    { name: '商丘市', children: [ { name: '梁园区' } ] },
    { name: '信阳市', children: [ { name: '浉河区' } ] },
    { name: '周口市', children: [ { name: '川汇区' } ] },
    { name: '驻马店市', children: [ { name: '驿城区' } ] },
    { name: '济源市', children: [ { name: '济源市' } ] },
  ]},

  { name: '湖北省', children: [
    { name: '武汉市', children: [ { name: '江岸区' }, { name: '江汉区' }, { name: '硚口区' }, { name: '汉阳区' }, { name: '武昌区' }, { name: '青山区' }, { name: '洪山区' }, { name: '东西湖区' }, { name: '蔡甸区' }, { name: '江夏区' }, { name: '黄陂区' }, { name: '新洲区' } ] },
    { name: '黄石市', children: [ { name: '黄石港区' }, { name: '西塞山区' }, { name: '下陆区' } ] },
    { name: '十堰市', children: [ { name: '茅箭区' }, { name: '张湾区' } ] },
    { name: '宜昌市', children: [ { name: '西陵区' }, { name: '伍家岗区' }, { name: '夷陵区' } ] },
    { name: '襄阳市', children: [ { name: '襄城区' }, { name: '樊城区' }, { name: '襄州区' } ] },
    { name: '鄂州市', children: [ { name: '鄂城区' }, { name: '华容区' } ] },
    { name: '荆门市', children: [ { name: '东宝区' }, { name: '掇刀区' } ] },
    { name: '孝感市', children: [ { name: '孝南区' } ] },
    { name: '荆州市', children: [ { name: '沙市区' }, { name: '荆州区' } ] },
    { name: '黄冈市', children: [ { name: '黄州区' } ] },
    { name: '咸宁市', children: [ { name: '咸安区' } ] },
    { name: '随州市', children: [ { name: '曾都区' } ] },
    { name: '恩施州', children: [ { name: '恩施市' } ] },
    { name: '仙桃市' },
    { name: '潜江市' },
    { name: '天门市' },
    { name: '神农架林区' },
  ]},
  { name: '湖南省', children: [
    { name: '长沙市', children: [ { name: '芙蓉区' }, { name: '天心区' }, { name: '岳麓区' }, { name: '开福区' } ] },
    { name: '株洲市', children: [ { name: '天元区' }, { name: '芦淞区' } ] },
    { name: '湘潭市', children: [ { name: '岳塘区' } ] },
    { name: '衡阳市', children: [ { name: '蒸湘区' } ] },
    { name: '邵阳市', children: [ { name: '大祥区' } ] },
    { name: '岳阳市', children: [ { name: '岳阳楼区' } ] },
    { name: '常德市', children: [ { name: '武陵区' } ] },
    { name: '张家界市', children: [ { name: '永定区' } ] },
    { name: '益阳市', children: [ { name: '赫山区' } ] },
    { name: '郴州市', children: [ { name: '北湖区' } ] },
    { name: '永州市', children: [ { name: '冷水滩区' } ] },
    { name: '怀化市', children: [ { name: '鹤城区' } ] },
    { name: '娄底市', children: [ { name: '娄星区' } ] },
    { name: '湘西州', children: [ { name: '吉首市' } ] },
  ]},
  { name: '广东省', children: [
    { name: '广州市', children: [ { name: '越秀区' }, { name: '天河区' }, { name: '海珠区' }, { name: '白云区' }, { name: '番禺区' } ] },
    { name: '韶关市', children: [ { name: '浈江区' } ] },
    { name: '深圳市', children: [ { name: '福田区' }, { name: '南山区' }, { name: '罗湖区' }, { name: '宝安区' }, { name: '龙岗区' } ] },
    { name: '珠海市', children: [ { name: '香洲区' }, { name: '金湾区' } ] },
    { name: '汕头市', children: [ { name: '金平区' }, { name: '龙湖区' } ] },
    { name: '佛山市', children: [ { name: '禅城区' }, { name: '南海区' }, { name: '顺德区' } ] },
    { name: '江门市', children: [ { name: '蓬江区' } ] },
    { name: '湛江市', children: [ { name: '赤坎区' } ] },
    { name: '茂名市', children: [ { name: '茂南区' } ] },
    { name: '肇庆市', children: [ { name: '端州区' } ] },
    { name: '惠州市', children: [ { name: '惠城区' } ] },
    { name: '梅州市', children: [ { name: '梅江区' } ] },
    { name: '汕尾市', children: [ { name: '城区' } ] },
    { name: '河源市', children: [ { name: '源城区' } ] },
    { name: '阳江市', children: [ { name: '江城区' } ] },
    { name: '清远市', children: [ { name: '清城区' } ] },
    { name: '东莞市' },
    { name: '中山市' },
    { name: '潮州市', children: [ { name: '湘桥区' } ] },
    { name: '揭阳市', children: [ { name: '榕城区' } ] },
    { name: '云浮市', children: [ { name: '云城区' } ] },
  ]},
  { name: '广西', children: [
    { name: '南宁市', children: [ { name: '青秀区' }, { name: '兴宁区' }, { name: '西乡塘区' } ] },
    { name: '柳州市', children: [ { name: '城中区' }, { name: '鱼峰区' } ] },
    { name: '桂林市', children: [ { name: '秀峰区' }, { name: '象山区' } ] },
    { name: '梧州市', children: [ { name: '万秀区' } ] },
    { name: '北海市', children: [ { name: '海城区' } ] },
    { name: '防城港市', children: [ { name: '港口区' } ] },
    { name: '钦州市', children: [ { name: '钦南区' } ] },
    { name: '贵港市', children: [ { name: '港北区' } ] },
    { name: '玉林市', children: [ { name: '玉州区' } ] },
    { name: '百色市', children: [ { name: '右江区' } ] },
    { name: '贺州市', children: [ { name: '八步区' } ] },
    { name: '河池市', children: [ { name: '金城江区' } ] },
    { name: '来宾市', children: [ { name: '兴宾区' } ] },
    { name: '崇左市', children: [ { name: '江州区' } ] },
  ]},
  { name: '海南省', children: [
    { name: '海口市', children: [ { name: '秀英区' }, { name: '龙华区' }, { name: '琼山区' } ] },
    { name: '三亚市', children: [ { name: '吉阳区' }, { name: '天涯区' }, { name: '海棠区' } ] },
    { name: '三沙市' },
    { name: '儋州市' },
  ]},
  { name: '四川省', children: [
    { name: '成都市', children: [ { name: '锦江区' }, { name: '青羊区' }, { name: '金牛区' }, { name: '武侯区' }, { name: '成华区' } ] },
    { name: '自贡市', children: [ { name: '自流井区' } ] },
    { name: '攀枝花市', children: [ { name: '东区' } ] },
    { name: '泸州市', children: [ { name: '江阳区' } ] },
    { name: '德阳市', children: [ { name: '旌阳区' } ] },
    { name: '绵阳市', children: [ { name: '涪城区' }, { name: '游仙区' } ] },
    { name: '广元市', children: [ { name: '利州区' } ] },
    { name: '遂宁市', children: [ { name: '船山区' } ] },
    { name: '内江市', children: [ { name: '市中区' } ] },
    { name: '乐山市', children: [ { name: '市中区' } ] },
    { name: '南充市', children: [ { name: '顺庆区' } ] },
    { name: '眉山市', children: [ { name: '东坡区' } ] },
    { name: '宜宾市', children: [ { name: '翠屏区' } ] },
    { name: '广安市', children: [ { name: '广安区' } ] },
    { name: '达州市', children: [ { name: '通川区' } ] },
    { name: '雅安市', children: [ { name: '雨城区' } ] },
    { name: '巴中市', children: [ { name: '巴州区' } ] },
    { name: '资阳市', children: [ { name: '雁江区' } ] },
    { name: '阿坝州', children: [ { name: '马尔康市' } ] },
    { name: '甘孜州', children: [ { name: '康定市' } ] },
    { name: '凉山州', children: [ { name: '西昌市' } ] },
  ]},
  { name: '贵州省', children: [
    { name: '贵阳市', children: [ { name: '南明区' }, { name: '云岩区' }, { name: '观山湖区' } ] },
    { name: '六盘水市', children: [ { name: '钟山区' } ] },
    { name: '遵义市', children: [ { name: '红花岗区' }, { name: '汇川区' } ] },
    { name: '安顺市', children: [ { name: '西秀区' } ] },
    { name: '毕节市', children: [ { name: '七星关区' } ] },
    { name: '铜仁市', children: [ { name: '碧江区' } ] },
    { name: '黔西南州', children: [ { name: '兴义市' } ] },
    { name: '黔东南州', children: [ { name: '凯里市' } ] },
    { name: '黔南州', children: [ { name: '都匀市' } ] },
  ]},
  { name: '云南省', children: [
    { name: '昆明市', children: [ { name: '五华区' }, { name: '盘龙区' }, { name: '官渡区' }, { name: '西山区' } ] },
    { name: '曲靖市', children: [ { name: '麒麟区' } ] },
    { name: '玉溪市', children: [ { name: '红塔区' } ] },
    { name: '保山市', children: [ { name: '隆阳区' } ] },
    { name: '昭通市', children: [ { name: '昭阳区' } ] },
    { name: '丽江市', children: [ { name: '古城区' } ] },
    { name: '普洱市', children: [ { name: '思茅区' } ] },
    { name: '临沧市', children: [ { name: '临翔区' } ] },
    { name: '楚雄州', children: [ { name: '楚雄市' } ] },
    { name: '红河州', children: [ { name: '蒙自市' } ] },
    { name: '文山州', children: [ { name: '文山市' } ] },
    { name: '西双版纳', children: [ { name: '景洪市' } ] },
    { name: '大理州', children: [ { name: '大理市' } ] },
    { name: '德宏州', children: [ { name: '芒市' } ] },
    { name: '怒江州', children: [ { name: '泸水市' } ] },
    { name: '迪庆州', children: [ { name: '香格里拉市' } ] },
  ]},
  { name: '西藏', children: [
    { name: '拉萨市', children: [ { name: '城关区' } ] },
    { name: '日喀则市', children: [ { name: '桑珠孜区' } ] },
    { name: '昌都市', children: [ { name: '卡若区' } ] },
    { name: '林芝市', children: [ { name: '巴宜区' } ] },
    { name: '山南市', children: [ { name: '乃东区' } ] },
    { name: '那曲市', children: [ { name: '色尼区' } ] },
    { name: '阿里地区', children: [ { name: '噶尔县' } ] },
  ]},
  { name: '陕西省', children: [
    { name: '西安市', children: [ { name: '新城区' }, { name: '碑林区' }, { name: '莲湖区' }, { name: '雁塔区' }, { name: '未央区' } ] },
    { name: '铜川市', children: [ { name: '耀州区' } ] },
    { name: '宝鸡市', children: [ { name: '渭滨区' } ] },
    { name: '咸阳市', children: [ { name: '秦都区' } ] },
    { name: '渭南市', children: [ { name: '临渭区' } ] },
    { name: '延安市', children: [ { name: '宝塔区' } ] },
    { name: '汉中市', children: [ { name: '汉台区' } ] },
    { name: '榆林市', children: [ { name: '榆阳区' } ] },
    { name: '安康市', children: [ { name: '汉滨区' } ] },
    { name: '商洛市', children: [ { name: '商州区' } ] },
  ]},
  { name: '甘肃省', children: [
    { name: '兰州市', children: [ { name: '城关区' }, { name: '七里河区' }, { name: '安宁区' } ] },
    { name: '嘉峪关市' },
    { name: '金昌市', children: [ { name: '金川区' } ] },
    { name: '白银市', children: [ { name: '白银区' } ] },
    { name: '天水市', children: [ { name: '秦州区' } ] },
    { name: '武威市', children: [ { name: '凉州区' } ] },
    { name: '张掖市', children: [ { name: '甘州区' } ] },
    { name: '平凉市', children: [ { name: '崆峒区' } ] },
    { name: '酒泉市', children: [ { name: '肃州区' } ] },
    { name: '庆阳市', children: [ { name: '西峰区' } ] },
    { name: '定西市', children: [ { name: '安定区' } ] },
    { name: '陇南市', children: [ { name: '武都区' } ] },
    { name: '临夏州', children: [ { name: '临夏市' } ] },
    { name: '甘南州', children: [ { name: '合作市' } ] },
  ]},
  { name: '青海省', children: [
    { name: '西宁市', children: [ { name: '城东区' }, { name: '城中区' }, { name: '城西区' } ] },
    { name: '海东市', children: [ { name: '乐都区' } ] },
    { name: '海北州', children: [ { name: '海晏县' } ] },
    { name: '黄南州', children: [ { name: '同仁市' } ] },
    { name: '海南州', children: [ { name: '共和县' } ] },
    { name: '果洛州', children: [ { name: '玛沁县' } ] },
    { name: '玉树州', children: [ { name: '玉树市' } ] },
    { name: '海西州', children: [ { name: '德令哈市' } ] },
  ]},
  { name: '宁夏', children: [
    { name: '银川市', children: [ { name: '兴庆区' }, { name: '金凤区' }, { name: '西夏区' } ] },
    { name: '石嘴山市', children: [ { name: '大武口区' } ] },
    { name: '吴忠市', children: [ { name: '利通区' } ] },
    { name: '固原市', children: [ { name: '原州区' } ] },
    { name: '中卫市', children: [ { name: '沙坡头区' } ] },
  ]},
  { name: '新疆', children: [
    { name: '乌鲁木齐市', children: [ { name: '天山区' }, { name: '新市区' }, { name: '水磨沟区' } ] },
    { name: '克拉玛依市', children: [ { name: '克拉玛依区' } ] },
    { name: '吐鲁番市', children: [ { name: '高昌区' } ] },
    { name: '哈密市', children: [ { name: '伊州区' } ] },
    { name: '昌吉州', children: [ { name: '昌吉市' } ] },
    { name: '博尔塔拉州', children: [ { name: '博乐市' } ] },
    { name: '巴音郭楞州', children: [ { name: '库尔勒市' } ] },
    { name: '阿克苏地区', children: [ { name: '阿克苏市' } ] },
    { name: '克孜勒苏州', children: [ { name: '阿图什市' } ] },
    { name: '喀什地区', children: [ { name: '喀什市' } ] },
    { name: '和田地区', children: [ { name: '和田市' } ] },
    { name: '伊犁州', children: [ { name: '伊宁市' } ] },
    { name: '塔城地区', children: [ { name: '塔城市' } ] },
    { name: '阿勒泰地区', children: [ { name: '阿勒泰市' } ] },
  ]},
  { name: '台湾省', children: [
    { name: '台北市' },
    { name: '高雄市' },
    { name: '台中市' },
    { name: '台南市' },
    { name: '新北市' },
  ]},
  { name: '香港', children: [
    { name: '中西区' }, { name: '湾仔区' }, { name: '东区' }, { name: '南区' },
    { name: '油尖旺区' }, { name: '九龙城区' }, { name: '观塘区' },
    { name: '沙田区' }, { name: '元朗区' },
  ]},
  { name: '澳门', children: [
    { name: '澳门半岛' }, { name: '离岛' },
  ]},
];
